# Generated by Django 3.2.9 on 2021-11-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='article',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단고정'),
        ),
    ]
