# Generated by Django 3.2.9 on 2021-11-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0005_alter_user_recommended_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommended_movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
